{{- if and (not .Values.tlsIssuer.production) (.Values.tlsIssuer.cluster)}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "{{ .Values.tlsIssuer.email }}"
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - selector:
        dnsNames:
          - "*.{{ .Values.tlsIssuer.domain }}"
          - "{{ .Values.tlsIssuer.domain }}"
      dns01:
{{- if eq .Values.tlsIssuer.provider "cloudDNS" }}
        cloudDNS:
          project: {{ .Values.tlsIssuer.cloudDNS.project }}
{{- end }}

{{- if eq .Values.tlsIssuer.provider "route53" }}
        route53:
          region: {{ .Values.tlsIssuer.route53.region }}
{{- end }}

{{- if eq .Values.tlsIssuer.provider "azureDNS" }}
        azureDNS:
          subscriptionID: {{ .Values.tlsIssuer.azureDNS.subscriptionId }}
          resourceGroupName: {{ .Values.tlsIssuer.azureDNS.resourceGroup }}
          hostedZoneName: {{ .Values.tlsIssuer.azureDNS.domain }}
{{- end }}

{{- if eq .Values.tlsIssuer.provider "cloudflare" }}
        cloudflare:
          email: {{ .Values.tlsIssuer.cloudflare.email }}
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
{{- end }}
{{- end }}