{{- if not .Values.tlsIssuer.production }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "tls-{{ .Values.tlsIssuer.domain | replace "." "-" }}-s"
  labels:
    jenkins.io/letsencrypt-service: staging
spec:
  secretName: "tls-{{ .Values.tlsIssuer.domain | replace "." "-" }}-s"
  issuerRef:
    name: letsencrypt-staging
{{- if .Values.tlsIssuer.cluster }}
    kind: ClusterIssuer
{{- end }}
  commonName: "*.{{ .Values.tlsIssuer.domain }}"
  dnsNames:
  - "*.{{ .Values.tlsIssuer.domain }}"
  - "{{ .Values.tlsIssuer.domain }}"
{{- end }}
